#define BAUDRATE 115200
#define PLACEHOLDER_COLOR_SPECTRUM "PLACEHOLDER_COLOR_SPECTRUM"
#define PLACEHOLDER_RGB "PLACEHOLDER_RGB"
#define PLACEHOLDER_HEX "PLACEHOLDER_HEX"
#define WAITING "Waiting for response..."
#define WIFI_DELAY 500