#define SERIAL_MY_IP "My IP is "
#define SERIAL_CAPTURE "Captured: "
#define SERIAL_CALIBRATION_BLACK "Black calibrated\n"
#define SERIAL_CALIBRATION_WHITE "White calibrated\n"
#define SERIAL_CONNECTED "Connected with IP: "
#define SERIAL_CONNECTION_FAILED "Connection to host failed\n"
#define SERIAL_CONNECTION_SUCCEED "Connected to server successful!\n"
#define SERIAL_RESPONSE "Response: "
#define SERIAL_ENTER "\n"
#define SERIAL_DISCONNECTED "Disconnecting...\n"