#define SERIAL_MY_IP "My IP is "
#define SERIAL_CAPTURE "Captured: "
#define SERIAL_CALIBRATION_BLACK "Black calibrated\n"
#define SERIAL_CALIBRATION_WHITE "White calibrated\n"
#define SERIAL_CONNECTED "Connected with IP: "
#define SERIAL_ENTER "\n"